STATUSES = (
        ('draft', 'Draft'),
        ('live', 'Live'),
        ('canceled', 'Canceled'),
        ('started', 'Started'),
        ('ended', 'Ended'),
    )

EVENT_TYPES = (
    ('attraction', 'Attraction'),
    ('camp_trip', 'Camp or Trip'),
    ('class_training_workshop', 'Classi Training or Workshop'),
    ('concert_performance', 'Concert or Performance'),
    ('conference', 'Conference'),
    ('dinner_gala', 'Dinner or Gala '),
    ('festival_fair', 'Festival or Fair'),
    ('game_competition', 'Game or Competition'),
    ('meeting_networking', 'Meeting or Networking Event'),
    ('party', 'Party or Social Gathering'),
    ('race_endurance', 'Race or Endurance Event'),
    ('rally', 'Rally'),
    ('screening', 'Screening'),
    ('seminar_talk', 'Seminar or Talk'),
    ('tournament', 'Tournament'),
    ('other', 'Other'),
)

EVENT_TOPICS = (
    ('auto_boat_air', 'Auto, Boat & Air'),
    ('business', 'Business & Professionel'),
    ('auto_boat_air', 'Charity & Causes'),
    ('auto_boat_air', 'Comunity & Culture'),
    ('auto_boat_air', 'Family & Education'),
    ('auto_boat_air', 'Fashion & Beauty'),
    ('auto_boat_air', 'Film, Media & Entertainment'),
    ('auto_boat_air', 'Food & Drink'),
    ('auto_boat_air', 'Government & Politics'),
    ('auto_boat_air', 'Healt & Wellness'),
    ('auto_boat_air', 'Hobbies & Special Interest'),
    ('auto_boat_air', 'Home & Life Style'),
    ('auto_boat_air', 'Music'),
    ('auto_boat_air', 'Performing & Visual Arts'),
    ('auto_boat_air', 'Religion'),
    ('auto_boat_air', 'Science & Technology'),
    ('auto_boat_air', 'Sports & Fitness'),
    ('auto_boat_air', 'Travel & Outdoor'),
)